
--BORRAR TABLAS

drop table CIUDADANO CASCADE CONSTRAINTS;
drop table USUARIO CASCADE CONSTRAINTS;
drop table PLAN_DE_VACUNACION CASCADE CONSTRAINTS;
drop table MINISTERIO_DE_SALUD CASCADE CONSTRAINTS;
drop table PUNTO_VACUNACION CASCADE CONSTRAINTS;
drop table CITA CASCADE CONSTRAINTS;
drop table TRABAJADOR CASCADE CONSTRAINTS;
drop table VACUNA CASCADE CONSTRAINTS;
drop table OFICINA_REGIONAL_EPS CASCADE CONSTRAINTS;
drop table LIST_CONDICIONES_CIUDADANO CASCADE CONSTRAINTS;
drop table LIST_CONTRAINDICACIONES_VACUNA CASCADE CONSTRAINTS;
drop table CONDICION CASCADE CONSTRAINTS;
drop table TIPO_PUNTO_VACUNACION CASCADE CONSTRAINTS;
drop table ESTADO_VACUNACION CASCADE CONSTRAINTS;
drop table TRABAJO CASCADE CONSTRAINTS;
drop table PRIORIZACION CASCADE CONSTRAINTS;


--DELETE FROM CIUDADANO;