ALTER SESSION SET CURRENT_SCHEMA = ISIS2304D10202110; -- triana

--PLAN_DE_VACUNACION
INSERT INTO PLAN_DE_VACUNACION (NOMBRE, DESCRIPCION, FECHA_ACTUALIZACION) VALUES ('Plan 1 Colombia', 'Descripcion de prueba', TO_DATE('2021/04/07 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));

--MINISTERIO_SALUD
INSERT INTO MINISTERIO_DE_SALUD (PLAN_DE_VACUNACION) VALUES (1);

--CIUDADANO
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168160,'Santiago Triana', 'No vacunado', 'Andina', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168161,'Juan Sebastian Ramirez', 'No vacunado', 'Andina', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168162,'Alexander Amores', 'No vacunado', 'Andina', 0, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168163,'Maria Sandoval', 'No vacunado', 'Pacifica', 0, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168164,'Geronimo Gonzales', 'No vacunado', 'Pacifica', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168165,'Benedicta Ramirez', 'No vacunado', 'Pacifica', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168166,'Adolfo Perez', 'Vacunado', 'Amazonia', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168167,'Roberto Giraldo', 'Vacunado', 'Amazonia', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168168,'Nestor Guevara', 'Primera dosis', 'Caribe', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168169,'Marta Contreras', 'Primera dosis', 'Caribe', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168170,'Elisa Madrid', 'No vacunado', 'Caribe', 1, NULL, NULL, NULL);

--USUARIO
INSERT INTO USUARIO (USERNAME,CONTRASENA,CORREO,PLAN_DE_VACUNACION,CIUDADANO) VALUES ('a.trianaa','contrasena1','a.trianaa@uniandes.edu.co', 1, '1001168160');
INSERT INTO USUARIO (USERNAME,CONTRASENA,CORREO,PLAN_DE_VACUNACION,CIUDADANO) VALUES ('j.ramirezb','contrasena2','j.ramirez@uniandes.edu.co', 1, '1001168161');
INSERT INTO USUARIO (USERNAME,CONTRASENA,CORREO,PLAN_DE_VACUNACION,CIUDADANO) VALUES ('alemores','contrasena3','alemores@gmail.com', 1, '1001168162');
INSERT INTO USUARIO (USERNAME,CONTRASENA,CORREO,PLAN_DE_VACUNACION,CIUDADANO) VALUES ('maria123','contrasena4','maria123@yahoo.es', 1, '1001168163');


--TRABAJADOR
INSERT INTO TRABAJADOR (CEDULA, TRABAJO, ADMINISTRADOR_VACUANDES) VALUES (1001168160, 'Administrador plan de vacunacion', 1);
INSERT INTO TRABAJADOR (CEDULA, TRABAJO, ADMINISTRADOR_VACUANDES) VALUES (1001168161, 'Administrador punto vacunacion', 1);
INSERT INTO TRABAJADOR (CEDULA, TRABAJO, ADMINISTRADOR_VACUANDES) VALUES (1001168162, 'Administrador oficina punto regional eps', 1);
INSERT INTO TRABAJADOR (CEDULA, TRABAJO, ADMINISTRADOR_VACUANDES) VALUES (1001168163, 'Operador punto vacunacion', 1);

--OFICINA_REGIONAL_EPS
INSERT INTO OFICINA_REGIONAL_EPS (REGION, ADMINISTRADOR, CANTIDAD_VACUNAS_ACTUALES, PLAN_DE_VACUNACION) VALUES ('Andina', 'alemores', 10, 1);
INSERT INTO OFICINA_REGIONAL_EPS (REGION, ADMINISTRADOR, CANTIDAD_VACUNAS_ACTUALES, PLAN_DE_VACUNACION) VALUES ('Caribe', 'alemores', 0, 1);

--PUNTO_DE_VACUNACION
INSERT INTO PUNTO_VACUNACION (LOCALIZACION, CAPACIDAD_DE_ATENCION_SIMULTANEA, CAPACIDAD_DE_ATENCION_TOTAL_DIARIA, INFRAESTRUCTURA_PARA_DOSIS, CANTIDAD_VACUNAS_ENVIABLES, CANTIDAD_VACUNAS_ACTUALES, TIPO_PUNTO_VACUNACION, ADMINISTRADOR)
VALUES ('Cra 54#178-12 Oficina 1', 10, 500, 'Congeladores, Cubiculos separados', 500, 10, 'Centro de salud', 'j.ramirezb');
INSERT INTO PUNTO_VACUNACION (LOCALIZACION, CAPACIDAD_DE_ATENCION_SIMULTANEA, CAPACIDAD_DE_ATENCION_TOTAL_DIARIA, INFRAESTRUCTURA_PARA_DOSIS, CANTIDAD_VACUNAS_ENVIABLES, CANTIDAD_VACUNAS_ACTUALES, TIPO_PUNTO_VACUNACION, ADMINISTRADOR)
VALUES ('Calle 12#57-34', 30, 1500, 'Todos los necesarios', 3000, 0, 'Hospital', 'j.ramirezb');

--VACUNA
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);

--CITA
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA) VALUES (TO_DATE('2021/06/06 15:00:00', 'yyyy/mm/dd hh24:mi:ss'),1001168164,1,1);
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA) VALUES (TO_DATE('2021/06/06 15:00:00', 'yyyy/mm/dd hh24:mi:ss'),1001168164,1,2);

